<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Few seconds ago' => '',
    'Friday' => 'Пятница',
    'Monday' => 'Понедельник',
    'Saturday' => 'Суббота',
    'Sunday' => 'Воскресенье',
    'Thursday' => 'Четверг',
    'Today' => 'Сегодня',
    'Tomorrow' => 'Завтра',
    'Tuesday' => 'Вторник',
    'Wednesday' => 'Среда',
    '{0, plural, =1{1 day ago} other{# days ago}}' => '',
    '{0, plural, =1{1 hour ago} other{# hours ago}}' => '',
    '{0, plural, =1{1 minute ago} other{# minutes ago}}' => '',
    '{0, plural, =1{1 month ago} other{# months ago}}' => '',
    '{0, plural, =1{1 week ago} other{# weeks ago}}' => '',
    '{0, plural, =1{1 year ago} other{# years ago}}' => '',
    '{0, plural, =1{one second ago} other{# seconds ago}}' => '',
    '{day} April' => '{day} апреля',
    '{day} August' => '{day} августа',
    '{day} December' => '{day} декабря',
    '{day} February' => '{day} февраля',
    '{day} January' => '{day} января',
    '{day} July' => '{day} июля',
    '{day} June' => '{day} июня',
    '{day} March' => '{day} марта',
    '{day} May' => '{day} мая',
    '{day} November' => '{day} ноября',
    '{day} October' => '{day} октября',
    '{day} September' => '{day} сентября',
];