<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Few seconds ago' => 'Pirms dažām sekundēm',
    '{0, plural, =1{1 day ago} other{# days ago}}' => 'Pirms {0, plural, zero{# dienām} =1{dienas} one{# dienas} other{# dienām}}',
    '{0, plural, =1{1 hour ago} other{# hours ago}}' => 'Pirms {0, plural, zero{# stundām} =1{stundas} one{# stundas} other{# stundām}}',
    '{0, plural, =1{1 minute ago} other{# minutes ago}}' => 'Pirms {0, plural, zero{# minūtēm} =1{minūtes} one{# minūtes} other{# minūtēm}}',
    '{0, plural, =1{1 month ago} other{# months ago}}' => 'Pirms {0, plural, zero{# mēnešiem} =1{mēneša} one{# mēneša} other{# mēnešiem}}',
    '{0, plural, =1{1 week ago} other{# weeks ago}}' => 'Pirms {0, plural, zero{# nedēļām} =1{nedēļas} one{# nedēļas} other{# nedēļām}}',
    '{0, plural, =1{1 year ago} other{# years ago}}' => 'Pirms {0, plural, zero{# gadiem} =1{gada} one{# gada} other{# gadiem}}',
    '{0, plural, =1{one second ago} other{# seconds ago}}' => 'Pirms {0, plural, zero{# sekundēm} =1{sekundes} one{# sekundes} other{# sekundēm}}',
];
